const SIGN_UP_USER = 'SIGN_UP_USER';
const AUTH_USER_REQUESTED = 'AUTH_USER_STARTED';
const AUTH_USER_SUCCEED = 'AUTH_USER_SUCCEED';
const AUTH_USER_FAILURE = 'AUTH_USER_FAILED';
const SIGN_IN_USER = 'SIGN_IN_USER';
const SIGN_OUT_USER = 'SIGN_OUT_USER';

const AUTH_INPUT_CHANGED = 'AUTH_INPUT_CHANGED';

export default {
  SIGN_UP_USER,
  AUTH_USER_REQUESTED,
  AUTH_USER_SUCCEED,
  AUTH_USER_FAILURE,
  SIGN_IN_USER,
  SIGN_OUT_USER,
  AUTH_INPUT_CHANGED,
};
