const AUTH_USER_REQUESTED = 'AUTH_USER_STARTED';
const AUTH_USER_SUCCEED = 'AUTH_USER_SUCCEED';
const AUTH_USER_FAILURE = 'AUTH_USER_FAILED';

const SIGN_UP_USER = 'SIGN_UP_USER';
const SIGN_IN_USER = 'SIGN_IN_USER';
const SIGN_OUT_USER = 'SIGN_OUT_USER';

const AUTH_INPUT_CHANGED = 'AUTH_INPUT_CHANGED';

const USER_DATA_REQUESTED = 'USER_DATA_REQUESTED';
const USER_DATA_SUCCEED = 'USER_DATA_SUCCEED';
const USER_DATA_FAILURE = 'USER_DATA_FAILURE';

const USER_CHATS_REQUESTED = 'USER_CHATS_REQUESTED';
const USER_CHATS_SUCCEED = 'USER_CHATS_SUCCEED';
const USER_CHATS_FAILED = 'USER_CHATS_FAILED';

const CHAT_DATA_REQUESTED = 'CHAT_DATA_REQUESTED';
const CHAT_DATA_SUCCEED = 'CHAT_DATA_SUCCEED';
const CHAT_DATA_FAILURE = 'CHAT_DATA_FAILURE';

const CHATS_LIST_UPDATED = 'CHATS_LIST_UPDATED';

const MESSAGE_INPUT_CHANGED = 'MESSAGE_INPUT_CHANGED';
const MESSAGE_SEND_REQUESTED = 'MESSAGE_SEND_REQUESTED';
const MESSAGE_SEND_SUCCEED = 'MESSAGE_SEND_SUCCEED';
const MESSAGE_SEND_FAILED = 'MESSAGE_SEND_FAILED';

export default {
  SIGN_UP_USER,
  AUTH_USER_REQUESTED,
  AUTH_USER_SUCCEED,
  AUTH_USER_FAILURE,
  SIGN_IN_USER,
  SIGN_OUT_USER,
  AUTH_INPUT_CHANGED,
  USER_DATA_REQUESTED,
  USER_DATA_SUCCEED,
  USER_DATA_FAILURE,
  CHAT_DATA_REQUESTED,
  CHAT_DATA_SUCCEED,
  CHAT_DATA_FAILURE,
  USER_CHATS_REQUESTED,
  USER_CHATS_SUCCEED,
  USER_CHATS_FAILED,
  CHATS_LIST_UPDATED,
  MESSAGE_INPUT_CHANGED,
  MESSAGE_SEND_REQUESTED,
  MESSAGE_SEND_SUCCEED,
  MESSAGE_SEND_FAILED,
};
