const CREATE_USER = 'CREATE_USER';
const AUTH_USER_REQUESTED = 'AUTH_USER_STARTED';
const AUTH_USER_SUCCEED = 'AUTH_USER_SUCCEED';
const AUTH_USER_FAILURE = 'AUTH_USER_FAILED';

export default {
  CREATE_USER,
  AUTH_USER_REQUESTED,
  AUTH_USER_SUCCEED,
  AUTH_USER_FAILURE,
};
